services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: dinger
        POSTGRES_USER: kobe
        POSTGRES_PASSWORD: 42812
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
